apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | lower | dump }}
  annotations:
    github.com/project-slug: qwiklabs-gcp-02-b73e32ca483b/${{ values.name | lower }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:platform
  lifecycle: experimental
